package jp.he23inw3.asset.infrastructure.vertexai;

import com.google.genai.Client;
import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.GenerateContentResponse;
import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.ws.rs.core.MediaType;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import jp.he23inw3.asset.configuration.LifeLogConfig;
import jp.he23inw3.asset.domain.constant.UserMessageConstants;
import jp.he23inw3.asset.domain.exception.GatewayException;
import jp.he23inw3.asset.domain.gateway.GeminiGateway;
import jp.he23inw3.asset.domain.model.GeminiParseResult;
import jp.he23inw3.asset.infrastructure.common.MessageHelper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.eclipse.microprofile.faulttolerance.Retry;
import org.eclipse.microprofile.faulttolerance.Timeout;

/**
 * Vertex AI Gemini API を使用した GeminiGateway 実装。
 * <p>
 * Structured Outputs（JSON Schema 固定）により、解析結果を安定して取得する。
 */
@Slf4j
@ApplicationScoped
@RequiredArgsConstructor
public class VertexAiGeminiGatewayImpl implements GeminiGateway {

    private final LifeLogConfig config;

    private final Client client;

    private final GeminiPromptFactory promptFactory;

    private final GeminiResponseParser responseParser;

    private GenerateContentConfig parseConfig;

    private GenerateContentConfig reflectConfig;

    @Override
    @Retry
    @Timeout(value = 60, unit = ChronoUnit.SECONDS)
    public GeminiParseResult parse(String rawText, LocalDateTime now, String dayStatus) {
        String prompt = promptFactory.createParsePrompt(rawText, now, dayStatus);
        try {
            GenerateContentResponse response = client.models.generateContent(config.gemini().model(), prompt,
                    parseConfig);
            String jsonText = getTextFromResponse(response);
            log.debug(MessageHelper.getMessage("infra.gemini.response", jsonText));
            return responseParser.parse(jsonText);
        } catch (IOException e) {
            log.error(MessageHelper.getMessage("infra.gemini.parse.error"), e);
            throw new GatewayException(UserMessageConstants.GEMINI_JSON_PARSE_API_ERROR, e);
        } catch (Exception e) {
            log.error(MessageHelper.getMessage("infra.gemini.parse.error"), e);
            throw new GatewayException(UserMessageConstants.GEMINI_PARSE_API_ERROR, e);
        }
    }

    @Override
    @Retry
    @Timeout(value = 60, unit = ChronoUnit.SECONDS)
    public String generateMonthlyReport(String monthlySummaryText) {
        String prompt = promptFactory.createReflectionPrompt(monthlySummaryText);
        try {
            GenerateContentResponse response = client.models.generateContent(config.gemini().model(), prompt,
                    reflectConfig);
            return getTextFromResponse(response);
        } catch (Exception e) {
            log.error(MessageHelper.getMessage("infra.gemini.reflect.error", "unknown"), e);
            throw new GatewayException(UserMessageConstants.GEMINI_REFLECT_API_ERROR, e);
        }
    }

    @PostConstruct
    void init() {
        String modelName = config.gemini().model();

        // ライフログ解析用モデル（JSON Schema 指定）
        parseConfig = GenerateContentConfig.builder().responseMimeType(MediaType.APPLICATION_JSON)
                .responseSchema(promptFactory.createParseResponseSchema()).temperature(0.1F) // 決定論的挙動のため低め
                .build();

        // 月末振り返り用モデル（通常のテキスト応答）
        reflectConfig = GenerateContentConfig.builder().temperature(0.7F).build();

        log.info(MessageHelper.getMessage("infra.gemini.init", config.google().projectId(), config.gemini().location(),
                modelName));
    }

    @PreDestroy
    void close() {
        // Shared Client instance lifecycle is managed by CDI container/producer.
    }

    // ── プライベートヘルパー ─────────────────────────────────

    /**
     * 生成されたコンテンツレスポンスから安全にテキストを抽出します。
     *
     * @param response
     *            コンテンツ生成レスポンス
     * @return 抽出されたテキスト
     */
    private String getTextFromResponse(GenerateContentResponse response) {
        String text = response.text();
        if (StringUtils.isBlank(text)) {
            throw new GatewayException("No content generated by Gemini API");
        }
        return text;
    }
}
