name: CD - Backend

on:
  push:
    tags:
      - "v-*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Backend CI (Test Suite)
        uses: ./.github/actions/backend-ci
        with:
          working-directory: ./app/lifelog

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Authenticate with Google Cloud
        uses: ./.github/actions/gcp-auth
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: "Build and Deploy"
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          cd ${{ github.workspace }}
          V="${{ steps.get_version.outputs.VERSION }}"

          gcloud builds submit . \
            --config cloudbuild.yaml \
            --project "$PROJECT_ID" \
            --substitutions="_TAG=${V}" \
            --service-account="projects/${PROJECT_ID}/serviceAccounts/lifelog-cloudbuild-sa@${PROJECT_ID}.iam.gserviceaccount.com"
