name: CI - Backend

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!develop'
    tags-ignore:
      - 'v*'
    paths:
      - 'app/lifelog/**'
      - '.github/workflows/ci-backend.yml'
      - '.github/actions/backend-ci/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'app/lifelog/**'
      - '.github/workflows/ci-backend.yml'
      - '.github/actions/backend-ci/**'

jobs:
  test:
    if: |
      (github.event_name == 'pull_request' && (contains(github.head_ref, 'webapi') || contains(github.head_ref, 'batch') || contains(github.head_ref, 'backend'))) ||
      (github.event_name == 'push' && (contains(github.ref_name, 'webapi') || contains(github.ref_name, 'batch') || contains(github.ref_name, 'backend')))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Backend CI
        uses: ./.github/actions/backend-ci
        with:
          working-directory: ./app/lifelog
