name: CI - WebAPI

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!develop'
    tags-ignore:
      - 'v*'
    paths:
      - 'app/lifelog/**'
      - '.github/workflows/ci-webapi.yml'
      - '.github/actions/backend-ci/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'app/lifelog/**'
      - '.github/workflows/ci-webapi.yml'
      - '.github/actions/backend-ci/**'

jobs:
  test:
    if: |
      (github.event_name == 'pull_request' && contains(github.head_ref, 'webapi')) ||
      (github.event_name == 'push' && contains(github.ref_name, 'webapi'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Backend CI
        uses: ./.github/actions/backend-ci
        with:
          working-directory: ./app/lifelog
